defaults: &defaults
  adapter: mysql2
  username: root
  password:
  host: localhost

development:
  database: dm-perf-app_development
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: dm-perf-app_test
  <<: *defaults
production:
  database: dm-perf-app_production
  <<: *defaults
